apiVersion: v1
kind: Service

metadata:
  name: hello-kube-1-svc   #use this name instead of pod's IP

spec:
  selector:
    app: hello-kube-1 #pods with this lable
  ports:
    - port: 80        #Which port should the Service listen on?
      targetPort: 80  #Which Pod port should the Service forward the network traffic to?
                      #That is, when traffic arrives at the Service, it should forward the traffic to one of the Pods (randomly) on port 80.