apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-number-api-deployment-blue
  namespace: default
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: random-number-api-blue
  template:
    metadata:
      labels:
        app: random-number-api-blue
    spec:
      containers:
        - name: random-number-api
          image: aaghamohammadi/random-number-api:1.0.0
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 100Mi