apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config   ##name of configmap
data:
  redis.conf: |     #we dont need configmap/redis.conf anymore, this key is our configuration file name
    bind 0.0.0.0
    port 6379
    protected-mode no
    appendonly yes
